# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# Set to true to add reviewers from different groups to pull requests
useReviewGroups: true

# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewGroups:
  groupA:
    - dawn0114
    - twoequal0
    - smilee0114
  groupB:
    - smilee0114

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip

# A list of label, to add the entire review groups to reviewers
useAllReviewGroupsLabels:
  - 모두 리뷰어
