name: 'Auto Assign Bot'
description: 'Add assignees and reviewers when pull requests are opened.'
author: 'Dawn Lee'
inputs:
  repo-token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: false
  configuration-path:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'green'
